---
name: "CI"

on:
  push:
    branches: ["*"]
    # branches-ignore: ['release*', 'pull_request*', 'pullrequest*', 'pr*']
  pull_request:
    branches: ["*"]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest] # windows-latest

    # The type of runner that the job will run on
    name: build
    runs-on: "${{ matrix.os }}"

    steps:
      - name: build info
        run: echo "os ${{ matrix.os }}"

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          FILTER_REGEX_EXCLUDE: .*(vendor|\.old|\.vscode|\.idea).*
      